'use client';

import { useCallback, useEffect, useRef, useState } from 'react';

type Notification = { id: number; kind: 'success' | 'error' | 'info' | 'warning' | 'announcement'; title: string; content?: string | null; isRead: boolean; createdAt: string; announcementId?: number | null; forcePopup?: boolean };
type NotificationResponse = { notifications?: Notification[]; pendingAnnouncement?: Notification | null; unreadCount?: number; total?: number; page?: number; pageSize?: number };

function when(value: string) { const date = new Date(value.includes('T') ? value : value.replace(' ', 'T')); return Number.isNaN(date.getTime()) ? '' : date.toLocaleString('zh-CN', { month: 'numeric', day: 'numeric', hour: '2-digit', minute: '2-digit' }); }

export default function NotificationBell() {
  const [open, setOpen] = useState(false); const [items, setItems] = useState<Notification[]>([]); const [unread, setUnread] = useState(0); const [page, setPage] = useState(1); const [total, setTotal] = useState(0); const [pageSize, setPageSize] = useState(12); const [pendingAnnouncement, setPendingAnnouncement] = useState<Notification | null>(null); const centerRef = useRef<HTMLDivElement>(null);
  const apply = useCallback((data: NotificationResponse, fallbackPage = 1) => { setItems(data.notifications || []); setUnread(Number(data.unreadCount || 0)); setTotal(Number(data.total || 0)); setPage(Math.max(1, Number(data.page || fallbackPage))); setPageSize(Math.max(1, Number(data.pageSize || 12))); setPendingAnnouncement(data.pendingAnnouncement || null); }, []);
  const load = useCallback(async (targetPage = 1) => { const response = await fetch(`/api/notifications?page=${targetPage}&pageSize=12`); const data = await response.json().catch(() => ({})); if (response.ok) apply(data, targetPage); }, [apply]);
  useEffect(() => { void load(page); const timer = window.setInterval(() => void load(page), 15000); const receive = () => void load(1); window.addEventListener('app-notification', receive); return () => { window.clearInterval(timer); window.removeEventListener('app-notification', receive); }; }, [load, page]);
  const readAll = useCallback(async () => { const response = await fetch('/api/notifications', { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ all: true, excludeAnnouncements: true }) }); const data = await response.json().catch(() => ({})); if (response.ok) apply(data); }, [apply]);
  const readAnnouncement = useCallback(async (id: number) => { const response = await fetch('/api/notifications', { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ id }) }); const data = await response.json().catch(() => ({})); if (response.ok) apply(data); }, [apply]);
  useEffect(() => { if (!open) return; const closeOnOutsidePointer = (event: PointerEvent) => { if (centerRef.current && event.target instanceof Node && !centerRef.current.contains(event.target)) setOpen(false); }; const closeOnEscape = (event: KeyboardEvent) => { if (event.key === 'Escape') setOpen(false); }; document.addEventListener('pointerdown', closeOnOutsidePointer); document.addEventListener('keydown', closeOnEscape); return () => { document.removeEventListener('pointerdown', closeOnOutsidePointer); document.removeEventListener('keydown', closeOnEscape); }; }, [open]);
  const toggle = () => { if (open) { setOpen(false); return; } setOpen(true); void readAll(); };
  const pageCount = Math.max(1, Math.ceil(total / pageSize));
  return <div ref={centerRef} className="notification-center"><button type="button" className="notification-bell" aria-label={`通知中心${unread ? `，${unread} 条未读` : ''}`} aria-expanded={open} onClick={toggle}><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M18 9a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9M10 21h4" /></svg>{unread > 0 && <i>{unread > 99 ? '99+' : unread}</i>}</button>{open && <section className="notification-popover" role="dialog" aria-label="通知中心"><header><div><strong>通知中心</strong><small>打开后会自动标记普通通知为已读</small></div></header><div className="notification-list">{items.length ? items.map((item) => <article key={item.id} className={`notification-item ${item.kind} ${item.isRead ? 'read' : ''}`}><span aria-hidden="true" /><div><b>{item.title}</b>{item.content && <p>{item.content}</p>}<time>{when(item.createdAt)}</time></div></article>) : <div className="notification-empty">还没有通知。完成转录、复盘、导入或配音后，结果会显示在这里。</div>}</div>{total > pageSize && <footer className="notification-pagination"><button type="button" disabled={page <= 1} onClick={() => void load(page - 1)}>上一页</button><span>{page} / {pageCount}</span><button type="button" disabled={page >= pageCount} onClick={() => void load(page + 1)}>下一页</button></footer>}</section>}{pendingAnnouncement && <section className="announcement-live-overlay" role="alertdialog" aria-modal="true" aria-label="系统公告"><div className="announcement-live-backdrop" aria-hidden="true" /><div className="announcement-modal announcement-modal-live"><div className="announcement-modal-mark" aria-hidden="true">公告</div><button className="announcement-modal-close" type="button" aria-label="关闭并标记已读" onClick={() => void readAnnouncement(pendingAnnouncement.id)}>×</button><p className="announcement-modal-kicker">SYSTEM UPDATE</p><h2>{pendingAnnouncement.title}</h2><p className="announcement-modal-content">{pendingAnnouncement.content}</p><time>{when(pendingAnnouncement.createdAt)}</time><button className="announcement-modal-confirm" type="button" onClick={() => void readAnnouncement(pendingAnnouncement.id)}>我已阅读</button></div></section>}</div>;
}
