// @ts-nocheck
'use client';

import { ChangeEvent, useEffect, useMemo, useRef, useState } from 'react';

type Provider = 'bailian' | 'baidu';
type Settings = { publicBaseUrl: string; cloneUrl: string; websocketUrl: string; sambertWebsocketUrl: string; synthesisUrl: string; baiduTtsUrl: string; baiduCloneUrl: string; apiKey?: string; apiKeySet?: boolean; apiKeyPreview?: string; sambertApiKey?: string; sambertApiKeySet?: boolean; sambertApiKeyPreview?: string; baiduApiKey?: string; baiduApiKeySet?: boolean; baiduApiKeyPreview?: string; baiduSecretKey?: string; baiduSecretKeySet?: boolean; baiduSecretKeyPreview?: string };
type Question = { id: number; content: string; typeName: string };
type Voice = { id: number; questionId: number | null; name: string; kind: 'custom' | 'generated'; provider?: Provider; status: 'processing' | 'ready' | 'failed'; model?: string; voiceId?: string; hasSource?: boolean; hasOutput: boolean; error?: string };
type VoiceData = { settings: Settings; questions: Question[]; voices: Voice[] };
type SourceMode = 'clone' | 'preset';

const PRESET_MODELS = [
  { model: 'sambert-zhida-v1', label: '知达（男声） · sambert-zhida-v1' },
  { model: 'sambert-zhichu-v1', label: '知厨（男声） · sambert-zhichu-v1' },
] as const;
const BAIDU_EMOTIONS = [['', '默认 / 中性'], ['neutral', '中性'], ['happy', '快乐'], ['down', '悲伤'], ['angry', '愤怒'], ['surprise', '惊讶'], ['fear', '恐惧']];

async function requestJson(url: string, options?: RequestInit) { const response = await fetch(url, options); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error || '请求失败，请稍后重试。'); return data; }
const countText = (questions: Question[]) => questions.reduce((total, item) => total + item.content.length, 0);

export default function QuestionVoiceManagement() {
  const [data, setData] = useState<VoiceData | null>(null); const [settings, setSettings] = useState<Settings | null>(null); const [provider, setProvider] = useState<Provider>('bailian'); const [questionId, setQuestionId] = useState('');
  const [sourceMode, setSourceMode] = useState<SourceMode>('preset'); const [cloneVoiceId, setCloneVoiceId] = useState(''); const [presetModel, setPresetModel] = useState(PRESET_MODELS[0].model); const [customPresetModel, setCustomPresetModel] = useState('');
  const [name, setName] = useState('百炼 · 知达'); const [nameTouched, setNameTouched] = useState(false); const [instruction, setInstruction] = useState('沉稳、清晰、专业的面试老师语气，语速中等。');
  const [rate, setRate] = useState('1'); const [pitch, setPitch] = useState('1'); const [volume, setVolume] = useState('50'); const [format, setFormat] = useState('mp3'); const [extra, setExtra] = useState('{}');
  const [baiduPer, setBaiduPer] = useState('1'); const [baiduSpeed, setBaiduSpeed] = useState('5'); const [baiduPitch, setBaiduPitch] = useState('5'); const [baiduVolume, setBaiduVolume] = useState('5'); const [baiduEmotion, setBaiduEmotion] = useState('');
  const [cloneName, setCloneName] = useState('我的复刻音色'); const [clonePrefix, setClonePrefix] = useState('fishvoice'); const [cloneModel, setCloneModel] = useState('qwen-audio-3.0-tts-flash'); const [cloneDescription, setCloneDescription] = useState(''); const [cloneLanguage, setCloneLanguage] = useState('zh'); const [cloneFile, setCloneFile] = useState<File | null>(null);
  const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false); const [batchConfirmOpen, setBatchConfirmOpen] = useState(false); const cancelBatchRef = useRef(false);

  const load = async () => { const next = await requestJson('/api/question-voices') as VoiceData; setData(next); setSettings(next.settings); setQuestionId((value) => value || String(next.questions[0]?.id || '')); };
  useEffect(() => { void load().catch((error: Error) => setMessage(error.message)); }, []);
  const clonedVoices = useMemo(() => data?.voices.filter((voice) => voice.provider === provider && voice.kind === 'custom' && voice.status === 'ready' && voice.voiceId) || [], [data, provider]);
  const currentAudio = useMemo(() => data?.voices.filter((voice) => voice.kind === 'generated' && voice.questionId === Number(questionId)) || [], [data, questionId]);
  const characters = useMemo(() => countText(data?.questions || []), [data]); const activePresetModel = presetModel === '__custom__' ? customPresetModel.trim() : presetModel;
  const selectedModel = provider === 'baidu' ? sourceMode === 'clone' ? 'baidu-voice-clone' : 'baidu-duxiaoyu' : sourceMode === 'clone' ? 'qwen-audio-3.0-tts-flash' : activePresetModel; const selectedVoiceId = sourceMode === 'clone' ? cloneVoiceId : '';
  const canGenerate = Boolean(questionId && name.trim() && selectedModel && (sourceMode === 'preset' || selectedVoiceId) && !busy);

  useEffect(() => {
    if (nameTouched) return;
    if (provider === 'baidu') setName(sourceMode === 'clone' ? `百度 · ${clonedVoices.find((voice) => voice.voiceId === cloneVoiceId)?.name || '复刻音色'}` : `百度 · per=${baiduPer || '1'}`);
    else if (sourceMode === 'clone') setName(`百炼 · ${clonedVoices.find((voice) => voice.voiceId === cloneVoiceId)?.name || '复刻音色'}`);
    else setName(`百炼 · ${activePresetModel || 'Sambert'}`);
  }, [provider, sourceMode, cloneVoiceId, activePresetModel, clonedVoices, nameTouched, baiduPer]);

  function buildPayload(id: number) {
    let parsed: Record<string, unknown>;
    try { parsed = JSON.parse(extra || '{}'); if (!parsed || Array.isArray(parsed) || typeof parsed !== 'object') throw new Error(); } catch { throw new Error('额外参数必须是合法的 JSON 对象。'); }
    const parameters = provider === 'baidu'
      ? { ...parsed, per: sourceMode === 'clone' ? Number(selectedVoiceId) : Number(baiduPer), spd: Number(baiduSpeed), pit: Number(baiduPitch), volume: Number(baiduVolume), format, emotion: baiduEmotion }
      : { ...parsed, speech_rate: Number(rate) || 1, pitch_rate: Number(pitch) || 1, volume: Number(volume) || 50, format, ...(sourceMode === 'clone' && instruction.trim() ? { instruction: instruction.trim() } : {}) };
    return { action: 'synthesize', provider, questionId: id, name: name.trim(), model: selectedModel, voiceId: selectedVoiceId, parameters };
  }
  async function synthesize(id: number) { return requestJson('/api/question-voices', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(buildPayload(id)) }); }
  async function generateCurrent() { setBusy(true); try { const result = await synthesize(Number(questionId)); setData(result.state); setMessage(result.skipped ? '当前题目在该平台已有同名配音，已跳过。' : '题目配音已生成。'); } catch (error) { setMessage((error as Error).message); } finally { setBusy(false); } }
  async function generateAll() {
    if (!data) return; setBatchConfirmOpen(false); cancelBatchRef.current = false; setBusy(true);
    try { for (let index = 0; index < data.questions.length && !cancelBatchRef.current; index += 1) { setMessage(`正在生成 ${index + 1}/${data.questions.length}；可停止剩余队列。`); const result = await synthesize(data.questions[index].id); setData(result.state); } setMessage(cancelBatchRef.current ? '已停止队列；当前请求完成前无法中断，已完成的音频会保留。' : '批量配音完成。'); }
    catch (error) { setMessage((error as Error).message); } finally { setBusy(false); }
  }
  async function deleteVoice(id: number) { if (!confirm('确定删除这条语音记录及其本地音频文件吗？')) return; try { setData(await requestJson(`/api/question-voices?id=${id}`, { method: 'DELETE' })); setMessage('已删除。'); } catch (error) { setMessage((error as Error).message); } }
  async function retryClone(id: number) { setBusy(true); try { const result = await requestJson('/api/question-voices', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ action: 'retry-clone', id }) }); setData(result.state); setMessage('已重新创建复刻音色。'); } catch (error) { setMessage((error as Error).message); } finally { setBusy(false); } }
  async function uploadClone() { if (!cloneFile) { setMessage('请先选择用于复刻的声音样本。'); return; } setBusy(true); try { const form = new FormData(); form.set('action', 'clone'); form.set('provider', provider); form.set('name', cloneName); form.set('prefix', clonePrefix); form.set('targetModel', cloneModel); form.set('voiceDesc', cloneDescription); form.set('lang', cloneLanguage); form.set('audio', cloneFile); const response = await fetch('/api/question-voices', { method: 'POST', body: form }); const result = await response.json().catch(() => ({})); if (!response.ok) throw new Error(result.error || '上传或复刻失败。'); setData(result.state); setCloneFile(null); setMessage('复刻音色已创建并保存 voice ID。'); } catch (error) { setMessage((error as Error).message); } finally { setBusy(false); } }
  async function saveSettings() { if (!settings) return; setBusy(true); try { const result = await requestJson('/api/question-voices', { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ settings }) }); setData(result); setSettings(result.settings); setMessage(`${provider === 'baidu' ? '百度' : '百炼'}语音配置已保存。`); } catch (error) { setMessage((error as Error).message); } finally { setBusy(false); } }

  if (!data || !settings) return <div className="voice-loading">加载题目语音管理…</div>;
  const updateName = (value: string) => { setNameTouched(true); setName(value); };
  return <section className="voice-management"><header><h2>题目语音管理</h2><p>按平台管理预设音色和复刻音色。生成文件仅保存在服务器本地；同一题目、同一平台、同一配音名称只会生成一次。</p></header>
    {message && <div className="management-message">{message}</div>}
    <nav className="voice-provider-tabs" aria-label="语音平台"><button type="button" className={provider === 'bailian' ? 'active' : ''} onClick={() => { setProvider('bailian'); setSourceMode('preset'); setCloneVoiceId(''); setNameTouched(false); }}>百炼语音</button><button type="button" className={provider === 'baidu' ? 'active baidu' : ''} onClick={() => { setProvider('baidu'); setSourceMode('preset'); setCloneVoiceId(''); setNameTouched(false); }}>百度语音</button></nav>
    <details className="voice-service-details"><summary>展开 {provider === 'baidu' ? '百度' : '百炼'} 服务配置 <small>密钥仅在服务端保存，页面不会回显完整内容</small></summary>
      {provider === 'baidu' ? <section className="voice-settings-card"><div className="voice-settings-grid"><label>百度 API Key<input type="password" value={settings.baiduApiKey || ''} placeholder={settings.baiduApiKeySet ? `已保存：${settings.baiduApiKeyPreview || '已隐藏'}` : '输入后保存'} onChange={(event) => setSettings({ ...settings, baiduApiKey: event.target.value })} /></label><label>百度 Secret Key<input type="password" value={settings.baiduSecretKey || ''} placeholder={settings.baiduSecretKeySet ? `已保存：${settings.baiduSecretKeyPreview || '已隐藏'}` : '输入后保存'} onChange={(event) => setSettings({ ...settings, baiduSecretKey: event.target.value })} /></label><label className="wide">百度短文本合成地址<input value={settings.baiduTtsUrl || 'https://tsn.baidu.com/text2audio'} onChange={(event) => setSettings({ ...settings, baiduTtsUrl: event.target.value })} /></label><label className="wide">百度声音复刻地址<input value={settings.baiduCloneUrl || 'https://aip.baidubce.com/rest/2.0/speech/publiccloudspeech/v1/voice/clone/create'} onChange={(event) => setSettings({ ...settings, baiduCloneUrl: event.target.value })} /></label></div><button className="voice-save" disabled={busy} onClick={() => void saveSettings()}>保存百度配置</button></section> : <section className="voice-settings-card"><div className="voice-settings-grid"><label>公网访问地址<input value={settings.publicBaseUrl} onChange={(event) => setSettings({ ...settings, publicBaseUrl: event.target.value })} /></label><label>声音复刻 REST API<input value={settings.cloneUrl} onChange={(event) => setSettings({ ...settings, cloneUrl: event.target.value })} /></label><label className="wide">Qwen TTS Workspace WebSocket<input value={settings.websocketUrl} onChange={(event) => setSettings({ ...settings, websocketUrl: event.target.value })} /></label><label className="wide">Sambert Workspace WebSocket<input value={settings.sambertWebsocketUrl} onChange={(event) => setSettings({ ...settings, sambertWebsocketUrl: event.target.value })} /></label><label>Sambert API Key<input type="password" value={settings.sambertApiKey || ''} placeholder={settings.sambertApiKeySet ? `已保存：${settings.sambertApiKeyPreview || '已隐藏'}` : '留空则使用百炼 API Key'} onChange={(event) => setSettings({ ...settings, sambertApiKey: event.target.value })} /></label><label>百炼 API Key<input type="password" value={settings.apiKey || ''} placeholder={settings.apiKeySet ? `已保存：${settings.apiKeyPreview || '已隐藏'}` : '输入后保存'} onChange={(event) => setSettings({ ...settings, apiKey: event.target.value })} /></label></div><button className="voice-save" disabled={busy} onClick={() => void saveSettings()}>保存百炼配置</button></section>}
    </details>
    <section className="voice-workbench"><section className="voice-action-card clone"><h3>音色来源</h3><div className="voice-mode-tabs"><button type="button" className={sourceMode === 'preset' ? 'active' : ''} onClick={() => { setSourceMode('preset'); setNameTouched(false); }}>预设音色</button><button type="button" className={sourceMode === 'clone' ? 'active' : ''} onClick={() => { setSourceMode('clone'); setNameTouched(false); }}>复刻音色</button></div>{sourceMode === 'clone' ? <label>选择已复刻的 voice ID<select value={cloneVoiceId} onChange={(event) => { setCloneVoiceId(event.target.value); setNameTouched(false); }}><option value="">请选择复刻音色</option>{clonedVoices.map((voice) => <option key={voice.id} value={voice.voiceId}>{voice.name} · {voice.voiceId}</option>)}</select><small className="voice-helper">{provider === 'baidu' ? '百度复刻音色会作为 per 参数调用。' : 'Qwen 复刻音色会作为 voice ID 调用。'}</small></label> : provider === 'baidu' ? <><strong className="voice-platform-badge baidu">百度预设发音人</strong><label>发音人 per<input type="number" min="0" max="50000" value={baiduPer} onChange={(event) => { setBaiduPer(event.target.value); setNameTouched(false); }} /></label><small className="voice-helper">默认度小宇为 1；可填百度已开通发音人的 per，例如度小美 0、度逍遥基础版 3。请以账号已开通的音库为准。</small></> : <><label>Sambert 预设模型<select value={presetModel} onChange={(event) => { setPresetModel(event.target.value); setNameTouched(false); }}>{PRESET_MODELS.map((preset) => <option key={preset.model} value={preset.model}>{preset.label}</option>)}<option value="__custom__">其他已开通 Sambert 模型…</option></select></label>{presetModel === '__custom__' && <label>Sambert 模型名称<input value={customPresetModel} onChange={(event) => { setCustomPresetModel(event.target.value); setNameTouched(false); }} placeholder="例如 sambert-xxx-v1" /></label>}<small className="voice-helper">Sambert 的模型名已包含发音人，不会额外发送 voice ID。</small></>}</section>
      <section className="voice-action-card"><h3>生成参数</h3><label>配音名称（用于去重）<input value={name} onChange={(event) => updateName(event.target.value)} placeholder="例如：正常面试男声" /></label>{provider === 'baidu' ? <><div className="voice-parameters"><label>语速 spd<input type="number" min="0" max="15" value={baiduSpeed} onChange={(event) => setBaiduSpeed(event.target.value)} /></label><label>音调 pit<input type="number" min="0" max="15" value={baiduPitch} onChange={(event) => setBaiduPitch(event.target.value)} /></label><label>音量 vol<input type="number" min="0" max="9" value={baiduVolume} onChange={(event) => setBaiduVolume(event.target.value)} /></label><label>格式<select value={format} onChange={(event) => setFormat(event.target.value)}><option value="mp3">MP3</option><option value="wav">WAV</option><option value="pcm">PCM</option></select></label></div><label>情感（音色支持时生效）<select value={baiduEmotion} onChange={(event) => setBaiduEmotion(event.target.value)}>{BAIDU_EMOTIONS.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label></> : <><div className="voice-parameters"><label>语速<input type="number" min="0.5" max="2" step="0.05" value={rate} onChange={(event) => setRate(event.target.value)} /></label><label>音调<input type="number" min="0.5" max="2" step="0.05" value={pitch} onChange={(event) => setPitch(event.target.value)} /></label><label>音量<input type="number" min="0" max="100" value={volume} onChange={(event) => setVolume(event.target.value)} /></label><label>格式<select value={format} onChange={(event) => setFormat(event.target.value)}><option value="mp3">MP3</option><option value="wav">WAV</option><option value="pcm">PCM</option></select></label></div>{sourceMode === 'clone' && <label>Qwen 指令 instruction<textarea value={instruction} onChange={(event) => setInstruction(event.target.value)} /></label>}</>}<label>额外参数 JSON<textarea value={extra} onChange={(event) => setExtra(event.target.value)} placeholder='例如 {"bit_rate":128}' /></label></section>
      <section className="voice-action-card generate"><h3>生成配音</h3><label>题目<select value={questionId} onChange={(event) => setQuestionId(event.target.value)}>{data.questions.map((question) => <option key={question.id} value={question.id}>{question.typeName} · {question.content.slice(0, 42)}</option>)}</select></label><button type="button" disabled={!canGenerate} onClick={() => void generateCurrent()}>为当前题目生成</button>{busy ? <button type="button" className="voice-batch" onClick={() => { cancelBatchRef.current = true; setMessage('将在当前请求完成后停止剩余队列。'); }}>停止剩余队列</button> : <button type="button" className="voice-batch" disabled={!canGenerate} onClick={() => setBatchConfirmOpen(true)}>一键为全部题目配音</button>}<small>{data.questions.length} 道题，约 {characters} 字；同平台、同名称的已有配音会跳过。</small></section>
    </section>
    <section className="voice-workbench"><section className="voice-action-card clone"><h3>创建{provider === 'baidu' ? '百度' : '百炼'}复刻音色</h3><p>仅需成功创建一次，voice ID 会保存，之后在上方直接选择使用。{provider === 'baidu' ? ' 百度样本限制 5MB，中文建议使用 5–20 秒清晰录音。' : ''}</p><label>名称<input value={cloneName} onChange={(event) => setCloneName(event.target.value)} /></label>{provider === 'baidu' ? <><label>音色说明（可选）<input value={cloneDescription} onChange={(event) => setCloneDescription(event.target.value)} placeholder="例如：温柔、清晰的女声" /></label><label>音色语种<select value={cloneLanguage} onChange={(event) => setCloneLanguage(event.target.value)}><option value="zh">中文 / 中英文</option><option value="ja">日语</option></select></label></> : <><label>音色前缀<input value={clonePrefix} onChange={(event) => setClonePrefix(event.target.value)} /></label><label>目标 Qwen 模型<input value={cloneModel} onChange={(event) => setCloneModel(event.target.value)} /></label></>}<label>声音样本<input type="file" accept="audio/wav,audio/mpeg,audio/mp4,audio/ogg,audio/aac" onChange={(event: ChangeEvent<HTMLInputElement>) => setCloneFile(event.target.files?.[0] || null)} /></label><button type="button" disabled={busy || !cloneFile} onClick={() => void uploadClone()}>上传并创建复刻音色</button></section></section>
    <VoiceLibrary title="当前题目的配音" count={currentAudio.length}>{currentAudio.length === 0 ? <p className="voice-helper">当前题目还没有生成配音。</p> : currentAudio.map((voice) => <VoiceCard key={voice.id} voice={voice} onDelete={deleteVoice} />)}</VoiceLibrary>
    <VoiceLibrary title={`${provider === 'baidu' ? '百度' : '百炼'}复刻音色库`} count={data.voices.filter((voice) => voice.kind === 'custom' && voice.provider === provider).length}>{data.voices.filter((voice) => voice.kind === 'custom' && voice.provider === provider).map((voice) => <VoiceCard key={voice.id} voice={voice} onDelete={deleteVoice} onRetry={retryClone} busy={busy} />)}</VoiceLibrary>
    {batchConfirmOpen && <div className="voice-batch-confirm-backdrop" role="presentation"><section className="voice-batch-confirm-modal" role="dialog" aria-modal="true" aria-labelledby="voice-batch-title"><h3 id="voice-batch-title">确认批量生成？</h3><p>将使用「{provider === 'baidu' ? '百度 · 度小宇' : selectedModel}」为 {data.questions.length} 道题生成名称为「{name || '未命名'}」的配音，约 {characters} 字。</p><small>同一题目、同一平台、同一名称已有的配音会自动跳过。开始后可停止剩余队列，正在进行的请求会完成后再停止。</small><div className="voice-batch-confirm-actions"><button type="button" className="voice-batch" onClick={() => setBatchConfirmOpen(false)}>取消</button><button type="button" className="voice-save" disabled={!canGenerate} onClick={() => void generateAll()}>确认开始</button></div></section></div>}
  </section>;
}

function VoiceLibrary({ title, count, children }: { title: string; count: number; children: React.ReactNode }) { return <section className="voice-library"><div className="voice-library-head"><h3>{title}</h3><small>{count} 条</small></div><div className="voice-list">{children}</div></section>; }
function VoiceCard({ voice, onDelete, onRetry, busy }: { voice: Voice; onDelete: (id: number) => void; onRetry?: (id: number) => void; busy?: boolean }) { const status = voice.status === 'ready' ? '可播放' : voice.status === 'failed' ? '失败' : '生成中'; const audioKind = voice.kind === 'custom' ? 'source' : 'output'; return <article><header><div><strong>{voice.name}</strong><span className={`voice-status ${voice.status}`}>{status}</span></div><button type="button" className="voice-delete" onClick={() => onDelete(voice.id)}>删除</button></header><dl><div><dt>平台</dt><dd>{voice.provider === 'baidu' ? '百度' : '百炼'}</dd></div><div><dt>模型</dt><dd>{voice.model || '—'}</dd></div></dl>{((voice.kind === 'custom' && voice.hasSource) || (voice.kind === 'generated' && voice.hasOutput)) && <div className="voice-preview"><span>{voice.kind === 'custom' ? '原始样本' : '试听'}</span><audio controls src={`/api/question-voices/${voice.id}/audio?kind=${audioKind}`} /></div>}{voice.status === 'failed' && voice.kind === 'custom' && voice.hasSource && onRetry && <button type="button" className="voice-batch" disabled={busy} onClick={() => onRetry(voice.id)}>使用原样本重试</button>}{voice.error && <p className="voice-error">{voice.error}</p>}</article>; }
